# Site settings
title: 台湾菜
email: tengweicai@gmail.com
description: 日常生活和技术博客
url: "http://caitengwei.github.io" # the base hostname & protocol for your site
twitter_username: caitengwei
github_username:  caitengwei

# Build settings
markdown: kramdown
permalink: /:year/:month/:title/
